Pandas: A Very Basic Introduction
=================================

`pandas` is a Python library used to work with data.

In the previous notebook we used pandas to put information returned by the ONS API into a table so that it was easier to view.

In this notebook we will only look at a few basic pandas features:

- importing pandas
- creating a DataFrame
- viewing data
- checking rows and columns
- selecting columns
- selecting simple rows

There is **no ETL in this notebook**.

Import pandas
-------------

The usual way to import pandas is:

In [1]:
import pandas as pd

`pd` is simply a short name for pandas.

We can now use pandas commands by writing `pd.` followed by the command we need.

A DataFrame
-----------

A **DataFrame** is a table made of rows and columns.

This is the main pandas object we used in the ONS data acquisition notebook.

We can create a small DataFrame from Python data:

In [2]:
data = [
    {"area": "Peterborough", "year": 2021, "value": 82.1},
    {"area": "Cambridge", "year": 2021, "value": 84.3},
    {"area": "Leicester", "year": 2021, "value": 81.7},
    {"area": "Peterborough", "year": 2022, "value": 82.5},
    {"area": "Cambridge", "year": 2022, "value": 84.6}
]

df = pd.DataFrame(data)

df

           area  year  value
0  Peterborough  2021   82.1
1     Cambridge  2021   84.3
2     Leicester  2021   81.7
3  Peterborough  2022   82.5
4     Cambridge  2022   84.6

The variable `df` now contains a pandas DataFrame.

Each dictionary became one row.

The dictionary keys became the column names.

Viewing the first rows
----------------------

For large datasets we usually do not want to print every row.

`head()` shows the first five rows:

In [3]:
df.head()

           area  year  value
0  Peterborough  2021   82.1
1     Cambridge  2021   84.3
2     Leicester  2021   81.7
3  Peterborough  2022   82.5
4     Cambridge  2022   84.6

We can also choose how many rows to display:

In [4]:
df.head(3)

           area  year  value
0  Peterborough  2021   82.1
1     Cambridge  2021   84.3
2     Leicester  2021   81.7

This is the same pandas feature used in the earlier ONS notebook when we wrote:

    df.head(10)

Checking the size of the DataFrame
----------------------------------

`shape` tells us how many rows and columns are in the DataFrame.

In [5]:
df.shape

(5, 3)

The result is shown as:

    (rows, columns)

For example, `(5, 3)` means 5 rows and 3 columns.

Checking the column names
-------------------------

`columns` shows the names of all columns:

In [6]:
df.columns

Index(['area', 'year', 'value'], dtype='str')

Checking the data types
-----------------------

`dtypes` shows the type of data stored in each column.

In [7]:
df.dtypes

area         str
year       int64
value    float64
dtype: object

For example:

- text is usually stored as `object`
- whole numbers may be stored as `int`
- decimal numbers may be stored as `float`

Selecting one column
--------------------

Use square brackets and the column name:

In [8]:
df["area"]

0    Peterborough
1       Cambridge
2       Leicester
3    Peterborough
4       Cambridge
Name: area, dtype: str

The result is one pandas **Series**.

A Series is similar to one column of a DataFrame.

Selecting more than one column
------------------------------

To select several columns, put the column names inside a list:

In [9]:
df[["area", "value"]]

           area  value
0  Peterborough   82.1
1     Cambridge   84.3
2     Leicester   81.7
3  Peterborough   82.5
4     Cambridge   84.6

Selecting rows with a simple condition
--------------------------------------

We can ask pandas to show only rows that meet a condition.

For example, show only rows where the area is Peterborough:

In [10]:
df[df["area"] == "Peterborough"]

           area  year  value
0  Peterborough  2021   82.1
3  Peterborough  2022   82.5

Another example: show rows where the value is greater than 83:

In [11]:
df[df["value"] > 83]

        area  year  value
1  Cambridge  2021   84.3
4  Cambridge  2022   84.6

Simple summary information
--------------------------

`info()` gives a quick overview of the DataFrame:

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   area    5 non-null      str
 1   year    5 non-null      int64
 2   value   5 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 252.0 bytes

It shows information such as:

- number of rows
- column names
- whether values are present
- data types

For now, the important point is simply that `info()` helps us understand what is inside a DataFrame.

Quick Practice
--------------

Using the `df` DataFrame above:

1. Display the first 2 rows.
2. Display the column names.
3. Select only the `area` column.
4. Select the `area` and `year` columns.
5. Display only rows where `year` is 2022.